version: '3'

services:
  api:
    container_name: 50day_api
    restart: always
    build:
      context: .
    ports:
      - '80:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: url
    networks:
        - network
networks:
  network:
    driver: bridge
